CREATE TABLE mountains(
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE peaks (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
	name VARCHAR(50) NOT NULL,
	mountain_id INTEGER,
	CONSTRAINT fk_mountain_id FOREIGN KEY (mountain_id)
	REFERENCES mountains(id) 
	ON DELETE CASCADE
	
)